### ISSUE TITLE
Vendor list is not public

### ISSUE THREAD

**Issue by bholota** [smartadserver/smart-gdpr-cmp-android#22]
It would be easier to start only `ConsentToolPreferencesActivity` if vendor list from `ConsentManager` was public (or available by method).

**Comment by GuillaumeLaubier** [comment]
Sorry but I don't understand the needs.

If you want to retrieve the vendor list, you just have to register a `ConsentManagerListener` when calling `ConsentManager.getSharedInstance().configure()`. The only callback of that listener will give you the vendor list as soon as it is fetched.

**Comment by bholota** [comment]
What about case when user triggered `allowAllPurposes` but later he needs to start `ConsentToolPreferencesActivity` to change some options?

**Comment by GuillaumeLaubier** [comment]
That kind of behavior is already implemented in the demo app (see [here](https://github.com/smartadserver/smart-gdpr-cmp-android/blob/master/app/src/main/java/com/smartadserver/android/smartcmp/demoapp/MainActivity.java#L29)).
Once the vendor list is downloaded, you can call `showConsentTool()` on the `ConsentManager` whenever you want to display the CMP.

**Comment by bholota** [comment]
I know. But I want to use my UI instead `showConsentTool()` to have better UX.  I need to start `ConsentToolPreferencesActivity` from my custom button, with exactly same code that is used in `showConsentTool()`. Only private part is vendor list.

**Comment by GuillaumeLaubier** [comment]
Ok I better understand now. Fine for me, we will add a getter for the next release.
