### ISSUE TITLE
Is there any reason for minSDK 18

### ISSUE THREAD

**Issue by miroslav404** [smartadserver/smart-gdpr-cmp-android#7]
It is strange that smartCmp lib requires minSDK to be 18, and for example your SmartAdServer-Android-SDK-6.9 requires minSDK 16. Is there any reason to have minSDK 18 and not 16 on cmp lib?

**Comment by glaubier** [comment]
Indeed there is no specific reason having minSDK 18. It will be set to 16 in the next version.

**Comment by glaubier** [comment]
Fixed in the [v3](https://github.com/smartadserver/smart-gdpr-cmp-android/releases/tag/v3)
